### ISSUE TITLE
Expose both drupal_id and northstar_id when returning user object 

### ISSUE THREAD

**Issue by chloealee** [DoSomething/api#8]
Currently, `user` returns only the drupal_id. We want to keep both in the main class object as `drupal_id`, and `northstar_id`, but during the transforming phase, only expose the `northstar_id` as what gets assigned to `user->id`

**Comment by chloealee** [comment]
@aaronschachter @weerd is the above accurate?

**Comment by weerd** [comment]
Yep. Debatable whether we want to just call the `northstar_id` just `id` always, with the understanding it's coming from Northstar (since eventually we won't need to bother w/ a Drupal one).

Other thing to note that I didn't catch in prior PR that could cause problems is that right now, only the `ReportbackItem` class is exposing the Northstar using, but we're universally transforming and outputting all the Northstar data in the `transformUser()` method... So `Reportback` and `Kudos` endpoints are trying to pass NS info as well to that method, but they currently don't have it...

If you check the logs in `/admin/reports/dblog` there's probably PHP notices indicating that '$data->first_name, `$data->last_name`, `$data->photo`, and `$data->country` do not exist or couldn't be found after loading a `/reportback.json` or `/kudos.json` endpoint.

I think we should just update and create a dedicated function that just goes and grabs the stuff from Northstar based on drupal id (in like `dosomething_helpers.module` or somewhere universal that multiple modules have access to), and just call that in each of the classes when grabbing the user data.

**Comment by aaronschachter** [comment]
I think it makes sense for Northstar id to be our canonical DoSomething User id, +1 on using `id` instead of `northstar_id`

**Comment by angaither** [comment]
second @aaronschachter

**Comment by weerd** [comment]
:dancer:
